"""Add request_id column for legacy compatibility

Revision ID: d86e928e232a
Revises: 
Create Date: 2026-01-01 18:36:03.263043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86e928e232a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('request_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_requests_request_id'), 'requests', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_request_id'), table_name='requests')
    op.drop_column('requests', 'request_id')
    # ### end Alembic commands ###
