name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv pip install --system .[dev]
      - name: Check formatting
        run: python -m black ibp --check
      - name: Lint
        run: python -m pylint ibp
      - name: Typecheck
        run: python -m mypy ibp
